### ISSUE TITLE
Power sampling interval and PowerProfileAPI

### ISSUE THREAD

**Issue by lioujheyu** [GPUOpen-Tools/CodeXL#101] opened 2017-01-19 02:19 UTC
Hello,

When I set the sample interval as 10 ms for CodeXLPowerProfiler, the report value seems only get changed every 100 ms. Here is an output example. The command is `/opt/CodeXL_2.2-511/CodeXLPowerProfiler -P power -d 1 -T 10`

```
PROFILE RECORDS
RecordId,Timestamp,pcie-ctrl-power,mem-ctrl-power,total-apu-power,display-ctrl-power,cpu-cu0-power,igpu-power
1,18:46:24:913,   0.453,   1.125,  15.574,   0.000,   9.469,   4.527
2,18:46:24:923,   0.453,   1.125,  15.574,   0.000,   9.469,   4.527
3,18:46:24:933,   0.453,   1.125,  15.574,   0.000,   9.469,   4.527
4,18:46:24:943,   0.453,   1.125,  15.574,   0.000,   9.469,   4.527
5,18:46:24:953,   0.453,   1.125,  15.574,   0.000,   9.469,   4.527
6,18:46:24:963,   0.453,   1.125,  15.574,   0.000,   9.469,   4.527
7,18:46:24:973,   0.453,   1.125,  15.574,   0.000,   9.469,   4.527
8,18:46:24:983,   0.453,   1.125,  15.574,   0.000,   9.469,   4.527
9,18:46:24:993,   0.453,   1.125,  15.574,   0.000,   9.469,   4.527
10,18:46:25:003,   0.453,   1.125,  15.574,   0.000,   9.469,   4.527
11,18:46:25:013,   0.453,   1.098,  10.961,   0.000,   4.883,   4.527
12,18:46:25:023,   0.453,   1.098,  10.961,   0.000,   4.883,   4.527
13,18:46:25:033,   0.453,   1.098,  10.961,   0.000,   4.883,   4.527
14,18:46:25:043,   0.453,   1.098,  10.961,   0.000,   4.883,   4.527
15,18:46:25:053,   0.453,   1.098,  10.961,   0.000,   4.883,   4.527
16,18:46:25:063,   0.453,   1.098,  10.961,   0.000,   4.883,   4.527
17,18:46:25:073,   0.453,   1.098,  10.961,   0.000,   4.883,   4.527
18,18:46:25:083,   0.453,   1.098,  10.961,   0.000,   4.883,   4.527
19,18:46:25:093,   0.453,   1.098,  10.961,   0.000,   4.883,   4.527
20,18:46:25:103,   0.453,   1.098,  10.961,   0.000,   4.883,   4.527
```

Besides, I am also trying to use PowerProfileAPI to write my own power profiling tool. Although the `AMDTPwrGetMinimalTimerSamplingPeriod()` reports the minimum sampling interval is 10 ms as well, I constantly get error code `AMDT_ERROR_NODATA` from `AMDTPwrReadAllEnabledCounters()` using this 10 ms as the sampling period. The worst thing is that the system will get completely crashed in one minute after doing so. This also happen to the example code `CollectAllCounters.cpp` with changing variable samplingInterval to 10 from 100. But, using CodeXLPowerProfiler will not crash the system even with the flag `-T 10`. 
Checking /var/log/syslog does not give me any useful information regarding the system crash. 

BTW, my system is running Ubunu 14.04 with AMD APU A8-7410.

Any suggestion?

**Comment by aalok-agarwal** [comment] 2017-01-19 09:34
Hi Liou Jhe-Yu, 

Thanks for reporting these bugs.
We have found the root cause, in couple of days we will be pushing some changes to fix them.

I will let you know once changes are pushed, 

Regards
Aalok Agarwal

**Comment by aalok-agarwal** [comment] 2017-01-30 07:27
Hi Liou Jhe-Yu,

We have submitted the changes for the first issue reported by you. 
Please pull the latest changes from git to have the fix.

We are working on the second issue, will let you know once the issue is fixed.

Regards,

**Comment by aalok-agarwal** [comment] 2017-01-30 11:40
Hi Liou Jhe-Yu,

We have pushed some changes to fix both the issues reported by you.

With the latest git pull, you can observe that power values is changing regularly after 10 ms when we trigger command "CodeXLPowerProfiler -P power -d 1 -T 10".  
Crash oberved while using API AMDTPwrReadAllEnabledCounters is fixed now, please refer the latest example code at "CollectAllCounters.cpp" for using AMDTPwrReadAllEnabledCounters API correctly.

Regards,
Aalok

**Comment by lioujheyu** [comment] 2017-02-02 02:08
Hi aalok,

Thanks for the fix. Now the CXLPowerProfiler and CollectAllCounters.cpp work as expected. 

However, I still sometime experienced system crash. This usually happened when I use gdb to trace my program containing PowerProfilie API. I suspect the root cause is that the profiling procedure does not stop/close properly since I break the program in the middle of execution by the gdb. 

I just have another test run. Without correctly stoping/closing profiling by existing the program using gdb, the system stop responding in 10 minutes.

Please help to confirm this issue.

Thanks,
Jhe-Yu

**Comment by aalok-agarwal** [comment] 2017-02-06 05:01
Hi Jhe-Yu. 

Thanks for confirming the fix. 
We will try to replicate the crash seen by you while using gdb, will come back to you in some time.

Regards, 
Aalok

**Comment by aalok-agarwal** [comment] 2017-02-15 09:48
Hi Jhe-Yu, 

We were not able to reproduce the crash reported by you while using gdb.
Recently we have pushed a fix for a potential crash. Can you please try with the latest version and please let me know if the issue is still seen.

Regards,
Aalok

**Comment by lioujheyu** [comment] 2017-02-15 18:14
Hi aalok-agarwal,

I've tested the lastest build with the new power driver for couple hours. Haven't experienced any crash since then. Thanks for the work.

Jhe-Yu

**Comment by aalok-agarwal** [comment] 2017-02-16 05:34
Hi Jhe-Yu, 

Thanks for confirming the fix.

Regards, 
Aalok

**Closed by aalok-agarwal** 2017-02-16 05:34 UTC
